using FluentMigrator;

namespace Infrastructure.Database.Migrations;

[Migration(2, description: "Create rides table")]
public class CreateRideMigration : Migration
{
    public override void Up()
    {
        Execute.Sql("""
                    CREATE TABLE rides
                    (
                        ride_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        passenger_id        BIGINT NOT NULL,
                        pickup_latitude     DOUBLE PRECISION NOT NULL,
                        pickup_longitude    DOUBLE PRECISION NOT NULL,
                        dropoff_latitude    DOUBLE PRECISION NOT NULL,
                        dropoff_longitude   DOUBLE PRECISION NOT NULL,
                        status              ride_status NOT NULL,
                        assigned_driver_id  BIGINT NULL,
                        route_id            BIGINT NULL
                    );

                    CREATE INDEX idx_rides_passenger_id ON rides(passenger_id);
                    CREATE INDEX idx_rides_assigned_driver_id ON rides(assigned_driver_id);
                    CREATE INDEX idx_rides_status ON rides(status);
                    """);
    }

    public override void Down()
    {
        Execute.Sql("""
                        DROP TABLE IF EXISTS rides;
                    """);
    }
}